<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to suporte@tray.net.br so we can send you a copy immediately.
 *
 * @category   Tray
 * @package    Tray_CheckoutApi
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<script src="https://static.traycheckout.com.br/js/finger_print.js" type="text/javascript"></script>

<fieldset class="form-list" data-yapay="payment-form">
    <?php 
        $_code = $this->getMethodCode();
        $_standardPD = Mage::getSingleton('checkoutapi/standard');
        
        $totals = Mage::getSingleton('checkout/session')->getQuote()->collectTotals();  
        Mage::log('########################### Inicio Total Cart Data ###########################', null, 'traycheckout.log');
        Mage::log(Mage::getSingleton('checkout/session')->getQuote()->collectTotals()->getData(), null, 'traycheckout.log');
        Mage::log('########################### Fim Total Cart Data ###########################', null, 'traycheckout.log');
        $strTcPaymentMethods = $_standardPD->getConfigData("tcPaymentMethods");

        if($strTcPaymentMethods == "" || $strTcPaymentMethods == null){
            $tcPaymentMethods = explode(",","3,4,5,18,16,15,19,20,25");
        } else {
            $tcPaymentMethods = explode(",",$strTcPaymentMethods);
        }
    ?>

<style>

.cvv-what-is-this {
    position: relative;
    display: inline-block;
    bottom: 25px; /* Adjust the value to move the image up */
    left: 75px; /* Adjust the value to move the image to the right */
}

.tooltip-text {
    visibility: hidden;
    width: 240px;
    background-color: #ededed;
    color: #808080;
    text-align: center;
    border-radius: 6px;
    padding: 5px 0;
    position: absolute;
    z-index: 1;
    bottom: 30px; /* Adjust this value to control the distance from the link */
    left: 50%;
    margin-left: -130px;
    transition: visibility 0.3s ease-in-out;
}

.cvv-what-is-this:hover .tooltip-text {
    visibility: visible;
}

</style>
    <style>
       ul li.tcPaymentMethod {
    float: left;
    padding: 5px;
    width: 60px; /* Increase the width to your desired size */
    height: 60px; /* Increase the height to your desired size */
    text-align: center; /* Center the image horizontally */
}
        ul li input {
            float: left;
            margin-right: 5px;
        }
        ul li img.tcPaymentFlag {
            float: left;
            max-width: 100%;
            max-height: 100%;
            background-repeat: no-repeat;
            border-radius: 3px;
            background-color: #f3f3f3;
            box-shadow: 1px 1px 2px #ececec;
            opacity: 0.30;
            -moz-opacity: 0.30;
            filter: alpha(opacity=30);
        }
        ul li img.tcPaymentFlagSelected {
            opacity: 1 !important;
            -moz-opacity: 1 !important;
            filter: alpha(opacity=100) !important;
        }
        
        ul li img.visa,
        ul li img.mastercard,
        ul li img.american-express,
        ul li img.discover {
            width: 10px; /* Adjust the width as needed */
        }
        
        @media screen and (max-width: 768px) {
            ul li.tcPaymentMethod {
                min-width: 60px;
                padding: 5px;
            }
            ul li input {
                margin-right: 3px;
            }
            ul li img.tcPaymentFlag {
                /* Change these values to revert to the original horizontal layout */
                width: 46px;
                height: 29px;
            }
        }
    </style>

    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        
        <li class="forma_pagamento" style="float:left;">
            <ul>
                <li>
                    <label for="tcPaymentMethod"><?php echo Mage::helper('payment')->__('Selecione a forma de pagamento') ?> <span class="required">*</span></label><br/>
                    <input type="hidden" id="tcPaymentMethod" name="payment[traycheckout_payment_code_creditcard]" class="required-entry" value=""/>
                    <ul>
                    <?php
                        $imgSrc = "";
                        foreach ($tcPaymentMethods as $idTcPayment){
                            switch (intval($idTcPayment)){
                                case 3: $imgSrc = "visa";break;
                                case 4: $imgSrc = "mastercard";break;
                                case 5: $imgSrc = "american-express";break;
                                case 15: $imgSrc = "discover";break;
                                case 16: $imgSrc = "elo";break;
                                case 18: $imgSrc = "aura";break;
                                case 19: $imgSrc = "jcb";break;
                                case 20: $imgSrc = "hipercard";break;
                                case 25: $imgSrc = "hiper";break;
                            }
                    ?>
                        <li class="tcPaymentMethod" >                            
                            <img src="<?php echo $this->getSkinUrl('tray/checkoutapi/images/'.$imgSrc.'-flag.svg') ?>" class="tcPaymentFlag" id="tcPaymentFlag<?php echo $idTcPayment;?>">
                        </li>
                    <?php
                        }
                    ?>
                    </ul>
                </li>
            </ul>
        </li>
        <li id="displayCcInfo" style="display: inline-block;">
            <ul>

                <li>                   
                    <div class="input-box">
                        <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
                        <!-- <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="required-entry input-text validate-cc-number" value="<?php echo $this->getInfoData('cc_number');?>" onkeyup="identifyCreditCardTc(this.value.replace(/ /g,''))" onblur="getSplitValues('<?php echo number_format((float)$totals->grand_total, 2, '.',''); ?>',document.getElementById('tcPaymentMethod').value,'<?php echo Mage::getUrl('', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>')" onkeypress="somenteNumeros(event,this)" placeholder="&bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull;" autocomplete="off"/> -->
                        <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="required-entry input-text validate-cc-number" value="" onkeyup="identifyCreditCardTc(this.value.replace(/ /g,''))" onblur="getSplitValues('<?php echo number_format((float)$totals->grand_total, 2, '.',''); ?>',document.getElementById('tcPaymentMethod').value,'<?php echo Mage::getUrl('', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>')" onkeypress="somenteNumeros(event,this)" placeholder="&bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull;" autocomplete="off"/>
                    </div>
                </li>
                 <li>
                    <div class="input-box">
                        <label for="<?php echo $_code ?>_cc_owner"><?php echo Mage::helper('payment')->__('Name on Card') ?> <span class="required">*</span></label><br/>
                        <input type="text" title="<?php echo Mage::helper('payment')->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->getInfoData('cc_owner') ?>" onkeypress="return apenasLetras(event,this);" placeholder="Ex: José Silva" autocomplete="off" />
                    </div>
                </li>        
                <li>
                    <div class="input-box">
                        <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
                        <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" style="width:102px;" name="payment[cc_exp_year]" class="required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                        <div class="v-fix">
                            <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" maxlength="4" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" oninput="fingerPrint()" value="" />
                       <div>
   <a class="cvv-what-is-this">
    <?php echo $this->__('<svg width="6%" height="6%" viewBox="-0.5 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g stroke-linecap="round" stroke-linejoin="round"></g> <path d="M12 22.15C17.3295 22.15 21.65 17.8295 21.65 12.5C21.65 7.17042 17.3295 2.84998 12 2.84998C6.67043 2.84998 2.34998 7.17042 2.34998 12.5C2.34998 17.8295 6.67043 22.15 12 22.15Z" stroke="#0F0F0F" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M9 9.49999C9 7.66999 10.65 6.20999 12.54 6.54999C13.75 6.75999 14.74 7.75 14.95 8.96C15.26 10.71 14.04 12.26 12.4 12.48C12.16 12.51 11.99 12.73 11.99 12.97V14.51" stroke="#0F0F0F" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M12 16.5V18.5" stroke="#0F0F0F" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>') ?>
    <span class="tooltip-text">
        CVV | CVC - Possui 3 ou 4 dígitos
        <br>que fica na frente ou verso do cartão</br>
    </span>
</a>


    <input type="hidden" id="payment[traycheckout_finger_print]" name="payment[traycheckout_finger_print]" />
 </span>
  </div>

                </li>
                <li>
                    <div class="input-box">
                        <input type="hidden" id="<?php echo $_code ?>_split_value" name="payment[traycheckout_split_value]" value="<?php echo $this->getInfoData('traycheckout_split_value')?>"/>
                        <label for="<?php echo $_code ?>_split"><?php echo Mage::helper('payment')->__('Parcelas') ?> <span class="required">*</span></label><br/>
                        <select id="<?php echo $_code ?>_split" style="width:252px;" name="payment[traycheckout_split_number]" class="required-entry" onchange="document.getElementById('<?php echo $_code ?>_split_value').value = this.options[this.selectedIndex].text.replace(/.*R\$/,'').replace(/\,'.');">
                            <option value="">Parcela(s)</option>
                        </select>
                    </div>
                </li>
            </ul>
        </li>
    </ul>
    
</fieldset>

<script type="text/javascript">    
    window.yapay.FingerPrint({  });
    
    $$('input[name="payment[method]"], input[name="shipping_method"]').each(function(item,index){
        Element.observe(item,'change',function(){
            
            setTimeout(function(){ 
                var inputCCNumber = document.getElementById('traycheckoutapi_cc_number').value;
            
                identifyCreditCardTc(inputCCNumber.replace(/ /g,''));
                getSplitValues('<?php echo number_format((float)$totals->grand_total, 2, '.',''); ?>',document.getElementById('tcPaymentMethod').value,'<?php echo Mage::getUrl('', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>');
                
            }, 3000);
            
        });
    });

</script>
